apiVersion: v1
kind: Service
metadata:
  name: exmongodb
  labels:
    name: mongo
spec:
  type: LoadBalancer
  ports:
    - port: 30012
      nodePort: 30012
      targetPort: 27017
 # clusterIP: None
  selector:
    role: mongo