apiVersion: v1
kind: Service
metadata:
  name: my-strapi-svc
  labels:
    app: strapi
spec:
  type: LoadBalancer
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: strapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-strapi
  labels:
    app: strapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      nodeSelector:
        server-type: db
        
      containers:
        - name: strapi
          image: strapi/strapi
          env:
            - name:  DATABASE_NAME
              value: defaultdb
            - name: DATABASE_HOST
              value: expa-staging-do-user-2500157-0.db.ondigitalocean.com
            - name: DATABASE_PORT
              value: "25060"
            - name: DATABASE_USERNAME
              value: doadmin
            - name: DATABASE_PASSWORD
              value: show-password

          ports:
            - containerPort: 1337
        
              #                -e DATABASE_NAME=mongo \
              #                -e DATABASE_HOST=192.168.64.2  \
              #                -e DATABASE_PORT=30000 \
              #                -e DATABASE_USERNAME=admin \
              #                -e DATABASE_PASSWORD=pass \
              #                -p 890:1337 \