apiVersion: v1
kind: Service
metadata:
  name: devcon-strapi-svc
  labels:
    app: devcon
spec:
  type: LoadBalancer
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: devcon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcon-strapi
  labels:
    app: devcon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devcon
  template:
    metadata:
      labels:
        app: devcon
    spec:
      nodeSelector:
        server-type: db
        
      containers:
        - name: devcon
          image: kkt97/devcon-strapi:1.0
          envFrom:
            - configMapRef:
                name: mongohostconfig
          
          # env:
          #   - name:  DATABASE_NAME
          #     value: defaultdb
          #   - name: DATABASE_HOST
          #     value: expa-staging-do-user-2500157-0.db.ondigitalocean.com
          #   - name: DATABASE_PORT
          #     value: "25060"
          #   - name: DATABASE_USERNAME
          #     value: doadmin
          #   - name: DATABASE_PASSWORD
          #     value: show-password

          ports:
            - containerPort: 1337
        
              