
apiVersion: v1
kind: Pod
metadata:
  name: mtestcontainer
spec:
  containers:
    - name: mtestcontainer
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: mongohostconfig
  restartPolicy: Never
